apiVersion: v1
kind: Service
metadata:
  name: mv-auth-service
  namespace: wrld3d
spec:
  type: NodePort
  selector:
    app: mv-auth-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
