apiVersion: v1
kind: Service
metadata:
  name: mv-auth-dev-service
  namespace: wrld3d
spec:
  type: NodePort
  selector:
    app: mv-auth-dev-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
